function uniqueValues(values: string[]) {
  return Array.from(new Set(values.map((value) => value.trim()).filter(Boolean)))
}

export const LOCATION_SUGGESTIONS = uniqueValues([
  'Toronto, Canada',
  'Vancouver, Canada',
  'Montreal, Canada',
  'Ottawa, Canada',
  'Calgary, Canada',
  'Edmonton, Canada',
  'Halifax, Canada',
  'Winnipeg, Canada',
  'Quebec City, Canada',
  'Victoria, Canada',
  'New York, United States',
  'San Francisco, United States',
  'Los Angeles, United States',
  'Seattle, United States',
  'Austin, United States',
  'Chicago, United States',
  'Boston, United States',
  'Denver, United States',
  'Atlanta, United States',
  'Miami, United States',
  'Portland, United States',
  'Washington, DC, United States',
  'London, United Kingdom',
  'Manchester, United Kingdom',
  'Edinburgh, United Kingdom',
  'Berlin, Germany',
  'Munich, Germany',
  'Amsterdam, Netherlands',
  'Paris, France',
  'Barcelona, Spain',
  'Madrid, Spain',
  'Lisbon, Portugal',
  'Dublin, Ireland',
  'Copenhagen, Denmark',
  'Stockholm, Sweden',
  'Singapore',
  'Sydney, Australia',
  'Melbourne, Australia',
  'Auckland, New Zealand',
  'Tokyo, Japan',
])

export const TIMEZONE_SUGGESTIONS = uniqueValues([
  'America/Toronto',
  'America/Vancouver',
  'America/New_York',
  'America/Chicago',
  'America/Denver',
  'America/Los_Angeles',
  'America/Phoenix',
  'America/Mexico_City',
  'America/Bogota',
  'America/Lima',
  'America/Sao_Paulo',
  'Europe/London',
  'Europe/Dublin',
  'Europe/Amsterdam',
  'Europe/Berlin',
  'Europe/Paris',
  'Europe/Madrid',
  'Europe/Lisbon',
  'Europe/Copenhagen',
  'Europe/Stockholm',
  'Europe/Rome',
  'Europe/Warsaw',
  'Europe/Helsinki',
  'Europe/Athens',
  'Asia/Dubai',
  'Asia/Kolkata',
  'Asia/Singapore',
  'Asia/Hong_Kong',
  'Asia/Tokyo',
  'Asia/Seoul',
  'Australia/Sydney',
  'Australia/Melbourne',
  'Pacific/Auckland',
  'UTC',
])

export const REGION_SUGGESTIONS = uniqueValues([
  'Canada',
  'United States',
  'North America',
  'Latin America',
  'LATAM',
  'South America',
  'Europe',
  'United Kingdom',
  'Ireland',
  'Germany',
  'France',
  'Netherlands',
  'Spain',
  'Portugal',
  'Italy',
  'Nordics',
  'EMEA',
  'Middle East',
  'Africa',
  'APAC',
  'Asia',
  'Australia',
  'New Zealand',
  'Japan',
  'Singapore',
  'India',
  'Worldwide',
])
